services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: praia_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d praia_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://demo:demo@db:5432/praia_db
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  simulator:
    build: ./simulator
    depends_on:
      - api
    environment:
      API_URL: http://api:8000
    command: ["python", "simulator.py"]

volumes:
  pgdata: